version: '2'

services:

  nginx:
    image: nginx:alpine
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - suma
      - resta
    depends_on: 
      - suma
      - resta
    ports:
      - "5000:90" 

  suma:
    build: ./suma

  resta:
    build: ./resta